# Generated by Django 3.2 on 2022-10-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdkey_record',
            name='use_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
